- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      kubeconfig: '~/.kube/config'
      definition: ""
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      kubeconfig: '~/.kube/config'
      validate_certs: no
      namespace: default
      definition: ""

